modLoader = "javafml"
loaderVersion = "[43,)"
license = "Terrarium Licence"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
modId = "ad_astra"
version = "${version}"
displayName = "Ad Astra"
displayURL = "https://modrinth.com/mod/ad-astra"
logoFile = "icon.png"
authors = "Alex Nijjar"
credits = "CodexAdrian, Facu, Fizz, Giselle, Kekie6, Shrimp, SpaceStar, Squishy, ThatGravyBoat"
description = "Live long and prosper, Ad Astra!"

[[dependencies.ad_astra]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[${resourcefulconfig_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "botarium"
mandatory = true
versionRange = "[${botarium_version},)"
ordering = "NONE"
side = "BOTH"