modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/terrarium-earth/Ad-Astra/issues"
license = "Terrarium Licence"

[[mods]]
modId = "ad_astra"
version = "${version}"
displayName = "Ad Astra!"
authors = " Alex Nijjar, CodexAdrian, Facu, Fizz, Kekie6, Shrimp, SpaceStar, Squishy, ThatGravyBoat"
description = "Live long and prosper, Ad Astra!"
logoFile = "icon.png"

[[dependencies.ad_astra]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[1.0.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "botarium"
mandatory = true
versionRange = "[1.7.12,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ad_astra]]
modId = "resourcefullib"
mandatory = true
versionRange = "[1.1.17,)"
ordering = "NONE"
side = "BOTH"