name: Publish Release
on:
  workflow_dispatch:
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle Caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Get Version and Platform
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./gradle.properties"
          properties: "version enabledPlatforms minecraftVersion"

      - name: Publish Release
        run: ./gradlew publish --info
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload NeoForge Releases (Curse/Modrinth/Github)
        id: neoforge_release
        if: contains(steps.properties.outputs.enabledPlatforms, 'neoforge')
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSE_ID }}
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: ./neoforge/build/libs/!(*-@(dev|sources|dev-shadow)).jar
          name: "[NeoForge] Ad Astra ${{ steps.properties.outputs.version }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: changelog.md
          loaders: neoforge
          game-versions: ${{ steps.properties.outputs.minecraftVersion }}
          version-resolver: exact

          dependencies: |
            resourceful-lib | depends | *
            resourceful-config | depends | *
            botarium | depends | *
            shimmer | recommends | *

      - name: Upload Fabric Releases (Curse/Modrinth/Github)
        id: fabric_release
        if: contains(steps.properties.outputs.enabledPlatforms, 'fabric')
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSE_ID }}
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: ./fabric/build/libs/!(*-@(dev|sources|dev-shadow)).jar
          name: "[Fabric] Ad Astra ${{ steps.properties.outputs.version }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: changelog.md
          loaders: fabric
          game-versions: ${{ steps.properties.outputs.minecraftVersion }}
          version-resolver: exact

          dependencies: |
            fabric-api | depends | *
            resourceful-lib | depends | *
            resourceful-config | depends | *
            botarium | depends | *
            shimmer | recommends | *

      - name: Generate Discord Embed
        run: ./gradlew injectEmbed
        env:
          FORGE_RELEASE_URL: ${{ steps.neoforge_release.outputs.modrinth-version }}
          FABRIC_RELEASE_URL: ${{ steps.fabric_release.outputs.modrinth-version }}

      - name: Upload Discord Embed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: ./build/embed.json
